/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-09 10:25:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Docmed</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- header-start -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header-area \">\r\n");
      out.write("            <div class=\"header-top_area\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-6 col-md-6 \">\r\n");
      out.write("                            <div class=\"social_media_links\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-linkedin\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                            <div class=\"short_contact_list\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\"> <i class=\"fa fa-envelope\"></i> healthinsurance@gmail.com</a></li>\r\n");
      out.write("                                    <li><a href=\"#\"> <i class=\"fa fa-phone\"></i> +919898657465</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"sticky-header\" class=\"main-header-area\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-2\">\r\n");
      out.write("                            <div class=\"logo\">\r\n");
      out.write("                                <a href=\"index.html\">\r\n");
      out.write("                                    <img src=\"img/logo.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("                                <nav>\r\n");
      out.write("                                    <ul id=\"navigation\">\r\n");
      out.write("                                        <li><a class=\"active\" href=\"index.html\">home</a></li>\r\n");
      out.write("                                        <li><a href=\"Department.html\">My Plans</a></li>\r\n");
      out.write("                                        <li><a href=\"Doctors.html\">Hospitals</a></li>\r\n");
      out.write("                                        <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                                    \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                            <div class=\"Appointment\">\r\n");
      out.write("                                <div class=\"book_btn d-none d-lg-block\">\r\n");
      out.write("                                    <a class=\"popup-with-form\" href=\"#test-form\">Logout</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- header-end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- slider_area_start -->\r\n");
      out.write("    <div class=\"slider_area\">\r\n");
      out.write("        <div class=\"slider_active owl-carousel\">\r\n");
      out.write("            <div class=\"single_slider  d-flex align-items-center slider_bg_2\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <div class=\"slider_text \">\r\n");
      out.write("                                <h3> <span>Health Insurance</span> <br>\r\n");
      out.write("                                    For Whole Family </h3>\r\n");
      out.write("                                <p>In healthinsurance sector, service excellence is the facility of <br> the hospital as\r\n");
      out.write("                                    health insurance service provider.</p>\r\n");
      out.write("                                <a href=\"checkplan.jsp\" class=\"boxed-btn3\">Check Out The Latest Plans</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slider_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- service_area_start -->\r\n");
      out.write("    <div class=\"service_area\">\r\n");
      out.write("        <div class=\"container p-0\">\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-xl-4 col-md-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"flaticon-electrocardiogram\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>Hospital List</h3>\r\n");
      out.write("                        <p>Clinical excellence must be the priority for any Health Insurance service provider.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"boxed-btn3-white\">Check Out the Hospitals </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-4 col-md-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"flaticon-emergency-call\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>Emergency Care</h3>\r\n");
      out.write("                        <p>Clinical excellence must be the priority for any Health Insurance service provider.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"boxed-btn3-white\">+10 672 356 3567</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-4 col-md-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"flaticon-first-aid-kit\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>Chamber Service</h3>\r\n");
      out.write("                        <p>Clinical excellence must be the priority for any Health Insurance service provider.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"boxed-btn3-white\">Make an Appointment</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- service_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- welcome_docmed_area_start -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- welcome_docmed_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- offers_area_start -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- offers_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- testmonial_area_start -->\r\n");
      out.write("\r\n");
      out.write("    <!-- testmonial_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- business_expert_area_start  -->\r\n");
      out.write("    <div class=\"business_expert_area\">\r\n");
      out.write("        \r\n");
      out.write("     </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"border_bottom\">\r\n");
      out.write("                    <div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("                            <div class=\"tab-pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_info\">\r\n");
      out.write("                                                    <div class=\"icon\">\r\n");
      out.write("                                                        <i class=\"flaticon-first-aid-kit\"></i>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <h3>Leading edge care for Your family</h3>\r\n");
      out.write("                                                    <p>Esteem spirit temper too say adieus who direct esteem.\r\n");
      out.write("                                                        It esteems luckily picture placing drawing. Apartments frequently or motionless on\r\n");
      out.write("                                                        reasonable projecting expression.\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_thumb\">\r\n");
      out.write("                                                    <img src=\"img/about/business.png\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("                                    <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_info\">\r\n");
      out.write("                                                    <div class=\"icon\">\r\n");
      out.write("                                                        <i class=\"flaticon-first-aid-kit\"></i>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <h3>Leading edge care for Your family</h3>\r\n");
      out.write("                                                    <p>Esteem spirit temper too say adieus who direct esteem.\r\n");
      out.write("                                                        It esteems luckily picture placing drawing. Apartments frequently or motionless on\r\n");
      out.write("                                                        reasonable projecting expression.\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_thumb\">\r\n");
      out.write("                                                    <img src=\"img/about/business.png\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane fade\" id=\"contact\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("                                    <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_info\">\r\n");
      out.write("                                                    <div class=\"icon\">\r\n");
      out.write("                                                        <i class=\"flaticon-first-aid-kit\"></i>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <h3>Leading edge care for Your family</h3>\r\n");
      out.write("                                                    <p>Esteem spirit temper too say adieus who direct esteem.\r\n");
      out.write("                                                        It esteems luckily picture placing drawing. Apartments frequently or motionless on\r\n");
      out.write("                                                        reasonable projecting expression.\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-xl-6 col-md-6\">\r\n");
      out.write("                                                <div class=\"business_thumb\">\r\n");
      out.write("                                                    <img src=\"img/about/business.png\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- business_expert_area_end  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- expert_doctors_area_start -->\r\n");
      out.write("    <div class=\"expert_doctors_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"doctors_title mb-55\">\r\n");
      out.write("                        <h3>Expert Doctors</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"expert_active owl-carousel\">\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/2.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/3.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/4.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_expert\">\r\n");
      out.write("                            <div class=\"expert_thumb\">\r\n");
      out.write("                                <img src=\"img/experts/2.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"experts_name text-center\">\r\n");
      out.write("                                <h3>Mirazul Alom</h3>\r\n");
      out.write("                                <span>Neurologist</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- expert_doctors_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Emergency_contact start -->\r\n");
      out.write("    <div class=\"Emergency_contact\">\r\n");
      out.write("        <div class=\"conatiner-fluid p-0\">\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-xl-6\">\r\n");
      out.write("                    <div class=\"single_emergency d-flex align-items-center justify-content-center emergency_bg_1 overlay_skyblue\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <h3>For Any Emergency Contact</h3>\r\n");
      out.write("                            <p>Esteem spirit temper too say adieus.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info_button\">\r\n");
      out.write("                            <a href=\"#\" class=\"boxed-btn3-white\">+10 378 4673 467</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-6\">\r\n");
      out.write("                    <div class=\"single_emergency d-flex align-items-center justify-content-center emergency_bg_2 overlay_skyblue\">\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <h3>Make an Online Appointment</h3>\r\n");
      out.write("                            <p>Esteem spirit temper too say adieus.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info_button\">\r\n");
      out.write("                            <a href=\"#\" class=\"boxed-btn3-white\">Make an Appointment</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Emergency_contact end -->\r\n");
      out.write("\r\n");
      out.write("<!-- footer start -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("            <div class=\"footer_top\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-4 col-md-6 col-lg-4\">\r\n");
      out.write("                            <div class=\"footer_widget\">\r\n");
      out.write("                                <div class=\"footer_logo\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <img src=\"img/footer_logo.png\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                        Firmament morning sixth subdue darkness \r\n");
      out.write("                                        creeping gathered divide.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"socail_links\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"ti-facebook\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"ti-twitter-alt\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("    \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-2 offset-xl-1 col-md-6 col-lg-3\">\r\n");
      out.write("                            <div class=\"footer_widget\">\r\n");
      out.write("                                <h3 class=\"footer_title\">\r\n");
      out.write("                                        Departments\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Eye Care</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Skin Care</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Pathology</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Medicine</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Dental</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("    \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-2 col-md-6 col-lg-2\">\r\n");
      out.write("                            <div class=\"footer_widget\">\r\n");
      out.write("                                <h3 class=\"footer_title\">\r\n");
      out.write("                                        Useful Links\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                    <li><a href=\"#\"> Contact</a></li>\r\n");
      out.write("                                    <li><a href=\"#\"> Appointment</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                            <div class=\"footer_widget\">\r\n");
      out.write("                                <h3 class=\"footer_title\">\r\n");
      out.write("                                        Address\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    200, D-block, Green lane USA <br>\r\n");
      out.write("                                    +10 367 467 8934 <br>\r\n");
      out.write("                                    docmed@contact.com\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copy-right_text\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"footer_border\"></div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <p class=\"copy_right text-center\">\r\n");
      out.write("                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("<!-- footer end  -->\r\n");
      out.write("    <!-- link that opens popup -->\r\n");
      out.write("\r\n");
      out.write("    <!-- form itself end-->\r\n");
      out.write("    <form id=\"test-form\" class=\"white-popup-block mfp-hide\">\r\n");
      out.write("        <div class=\"popup_box \">\r\n");
      out.write("            <div class=\"popup_inner\">\r\n");
      out.write("                <h3>Make an Appointment</h3>\r\n");
      out.write("                <form action=\"#\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <input id=\"datepicker\" placeholder=\"Pick date\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <input id=\"datepicker2\" placeholder=\"Suitable time\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <select class=\"form-select wide\" id=\"default-select\" class=\"\">\r\n");
      out.write("                                <option data-display=\"Select Department\">Department</option>\r\n");
      out.write("                                <option value=\"1\">Eye Care</option>\r\n");
      out.write("                                <option value=\"2\">Physical Therapy</option>\r\n");
      out.write("                                <option value=\"3\">Dental Care</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <select class=\"form-select wide\" id=\"default-select\" class=\"\">\r\n");
      out.write("                                <option data-display=\"Doctors\">Doctors</option>\r\n");
      out.write("                                <option value=\"1\">Mirazul Alom</option>\r\n");
      out.write("                                <option value=\"2\">Monzul Alom</option>\r\n");
      out.write("                                <option value=\"3\">Azizul Isalm</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <input type=\"text\"  placeholder=\"Name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-6\">\r\n");
      out.write("                            <input type=\"text\"  placeholder=\"Phone no.\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <input type=\"email\"  placeholder=\"Email\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <button type=\"submit\" class=\"boxed-btn3\">Confirm</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!-- form itself end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("    <script src=\"js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <script src=\"js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/ajax-form.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/scrollIt.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"js/nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"js/gijgo.min.js\"></script>\r\n");
      out.write("    <!--contact js-->\r\n");
      out.write("    <script src=\"js/contact.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"js/mail-script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $('#datepicker').datepicker({\r\n");
      out.write("            iconsLibrary: 'fontawesome',\r\n");
      out.write("            icons: {\r\n");
      out.write("                rightIcon: '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $('#datepicker2').datepicker({\r\n");
      out.write("            iconsLibrary: 'fontawesome',\r\n");
      out.write("            icons: {\r\n");
      out.write("                rightIcon: '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("    $('.js-example-basic-multiple').select2();\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
